name: Printer Notification
version: 0.1
slug: printer_notification
description: Sends notifications to a network printer.
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
startup: application
boot: auto
options:
  printer_url: "ipp://192.168.0.71/ipp/print"
  message: "This is a test message"
schema:
  printer_url: str
  message: str
